### ISSUE TITLE
[Roots 3] Unable to add Pyre recipe with CT

### ISSUE THREAD

**Issue by al132mc** [EpicSquid/Roots#121]
I am trying to change the recipe for creating Stalicripe in the pyre, but it seems that I am unable to do so. Removing the old recipe works fine, but proceeding to add a new recipe doesn't. It neither shows up in JEI nor works when I try to insert the proper inputs anyway.

```
 mods.roots.Pyre.removeRecipe(<roots:stalicripe>*3);
 mods.roots.Pyre.addRecipe("g_stalicripe_blue",<roots:stalicripe>*2,
 [<minecraft:flint>,
  <contenttweaker:ice_crystal>,
  <roots:terra_moss>,
  <quark:root_dye>,
  <pyrotech:material:13>]);
```

crafttweaker.log shows the following
```
[POSTINITIALIZATION][CLIENT][INFO] Removing 1 Pyre Crafting Ritual Recipe(s) for <roots:stalicripe> * 3
[POSTINITIALIZATION][CLIENT][INFO] Adding 1 Pyre Crafting Ritual Recipe(s) for <roots:stalicripe> * 2
```

Finally, a JEI screenshot
![2019-06-30_10 47 34](https://user-images.githubusercontent.com/39097092/60399045-b340b100-9b24-11e9-8bae-1b15ff0c01e2.png)

**Comment by EpicSquid** [comment]
Huh. Interesting. I'll have a look since that definitelt used to work.

**Comment by duely** [comment]
I would also recommend using the original recipe name so the guidebook knows what recipe to look up.

**Comment by duely** [comment]
I've resolved this by, at my own initiative & Jared from CraftTweaker's suggestion, implementing it as a BaseAction instead of using the map removal as the injection of the recipe was happening at a weird time/improperly happening or just straight up not happening.

I wasn't able to test it with your exact code, as I didn't have those mods installed, but here's a modified (show in game) version of stalicripe: ![](https://i.imgur.com/X88v5VC.png)

***Please note that in order to not break the Patchouli book*** you should preserve the recipe name wherever possible. I'll aim to make this more flexible in the future by having Patchouli look up recipes based on items primarily.

As an example, here's the Patchouli page for stalicripe with the modified recipe: ![](https://i.imgur.com/ZQBa3Uw.png)

And here it is complaining about an invalid page: ![](https://i.imgur.com/WKutpcE.png)
