### ISSUE TITLE
[Suggestion] Wildwood weapons/tools/armor glow a greenish tint when enchanted

### ISSUE THREAD

**Issue by VallenFrostweaver** [EpicSquid/Roots#139]
Wildwood & Sylvan weapons/tools/armor glow a greenish tint when enchanted instead of the default vanilla purple.  I think this would make them much more "roots" specific and more aesthetic assuming it was noticeable but not toxic avenger bright either.

**Comment by duely** [comment]
[Nautilus](https://www.curseforge.com/minecraft/mc-mods/nautilus) is unfortunately still in Alpha, but I'll talk to Darkhax about potentially including it as a dependency. Otherwise the only way to achieve this functionality is through providing coremodding ourselves. 

That ideally would be nice though!

**Comment by duely** [comment]
This wouldn't be possible without using ASM or depending directly on Nautilus. It could be done as an option thing with Nautilus, which is a distinct possibility, but I'm not sure how many people would actually download it.

**Comment by VallenFrostweaver** [comment]
Ok. Nvm then. Thanks!
