### ISSUE TITLE
[Roots 3] Lava sets the player on fire while using Light Drifter 

### ISSUE THREAD

**Issue by LordErroi** [EpicSquid/Roots#143]
Specifically, the player will be set on fire immediately after Light Drifter ends and are returned to their original location after passing through lava during the spell.

**Comment by AnotherVagabond** [comment]
Honestly? I kind of like the idea of keeping this as a feature. Basically, when you're in the depths of the earth, don't go sending your spirit out willy-nilly, because fire (being a source of mysticism in itself, and one of the four prime elements) still exists in the spirit world. Maybe even expand this and deliberately do the same thing with regular fire sources too.

**Comment by duely** [comment]
This would make no sense lore-wise and just makes it frustrating for players to have a **GOTCHA!!** when using the spell.

**Comment by AnotherVagabond** [comment]
Well, it's up to the devs if they agree or not, but "fire=magic" is already
in the lore via elemental soil and an herb, and it's not a gotcha if the
book warns you about it (which it would if it were added as a feature).
