### ISSUE TITLE
major memory leak or lag in current version

### ISSUE THREAD

**Issue by Technify82** [EpicSquid/Roots#149]
I am a modpack creator (Treasurecraft), and as such I am always updating, testing and tweaking my pack. I recently updated all of the mods in my pack in including Roots. When I loaded the game I was getting this message "Can't keep up! Did the system time change, or is the server overloaded? Running 2651ms behind, skipping 53 tick(s)," but more like 50000ms behind.... I suspected Roots because I was getting another message randomlyAfter disabling Roots the game became playable again. Here is a modlist not including Roots:

[modlist_2019-13-07.pdf](https://github.com/EpicSquid/Roots/files/3389405/modlist_2019-13-07.pdf)

Here is a log with roots installed after updating (and crashing...):

[2019-07-13-1.log](https://github.com/EpicSquid/Roots/files/3389411/2019-07-13-1.log)

Thank-you

**Comment by EpicSquid** [comment]
Update both mystical lib and mystical world, then try reinstalling. I'm surprised it even boots! Are you using thr latest version of roots as well?

**Comment by Technify82** [comment]
Everything is updated (though Twitch). I've tried reinstalling twice now. That's why I figured I would mention it here. I disabled Roots but still have mystical lib and mystical world installed and active. Everything works fine without Roots.

**Comment by duely** [comment]
What version of Roots are you using?

**Comment by Technify82** [comment]
Roots-1.12.2-3.0.2.jar

**Comment by duely** [comment]
I did a quick google of the "root" error message and, as I suspected, it actually has nothing to do with Roots the mod. It's specifically referring to the "root" of the game. It's an error message that has been around since [1.7.2 and in Vanilla](https://www.minecraftforum.net/forums/support/server-support-and/1883781-can-someone-tell-me-what-this-error-is-and-if). 

`[19:02:00] [Server thread/INFO]: This world was saved with mod roots version 0.104 and it is now at version 1.12.2-3.0.2, things may not work well` this line here along with the considerable number of errors seems to imply that you've updated directly from Roots 2 to Roots 3, which could be problematic. 

Based on the fact that this error occurs immediately after logging into the single-player world: `[19:03:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 19380ms behind, skipping 387 tick(s)` I'm going to assume there is a root issue with your system.

Have you tried to see whether this occurs in a new world, instead of constantly reusing your existing world?

The large quantity of `[19:05:37] [Client thread/ERROR]: Got a genetic item with no genome, setting it to a default value.`
`[19:05:37] [Client thread/ERROR]: Got a genetic item with no genome, setting it to a default value.` seems to imply that there could be an issue there as well, but that's probably unrelated. 

```[19:05:45] [Client thread/ERROR]: Error thrown whilst accessing JEI internals!
java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getActiveAdvancedGuiHandlers(Lnet/minecraft/client/gui/inventory/GuiContainer;)Ljava/util/List;```

This error message seems to imply that you have some major conflict between your version of Code Chicken Lib and your version of JEI and what they're expecting to find. It's possible that your Twitch is set to only load release versions but the most recent version of JEI is alpha -- but I'm not entirely sure on that note. 

[Reddit does suggest](https://old.reddit.com/r/Minecraft/comments/5antet/memory_leak_or_severe_lag_in_my_world_help/) that (for 1.7.10 at least) these "root" error messages may be directly related to the number of loaded entities. `/forge entity list` will help you look at what they are. A good trick if you have a large number of item entities is to run `/tp @e[type=item] ~ ~ ~` which will print out the item's location and what the item is (though you will need to consult your log to see it).

Likewise, be aware that, when playing in single-player mode, "pausing" the game by hitting escape or alt-tabbing can cause the server to become extremely backlogged. I'm unsure of the specifics but I've encountered it myself in single-player worlds.

So, finally, have a look through the above suggestions, try creating a new world and ensuring you don't accidentally pause the game in any fashion, and then get back to us.

Otherwise, I don't see anything to indicate that any of the Mystic Mods (especially Roots) are specifically responsible for this, although it may be that something has become corrupted in the transition from Roots 2 -> Roots 3.

**Comment by Technify82** [comment]
Will I will try and let you know, thank-you

**Comment by Technify82** [comment]
I created a new world and everything seems to be working fine (with Roots installed). Oddly enough I'm not getting any hostile mob spawns...(I've encountered this before). I typed in /tp @e[type=item] ~ ~ ~ on a newly created world and had ~35 entities loaded in a non skyblock overworld. The genetic genome thing has been around for ages, it's a forestry, gendustry, binnie's mods thing (I basically ignore it). I think the genetic issue is related to looting chests or lootbags. I will absolutely will look into the JEI - Code Chicken Lib thing too (I noticed it but found little info related to it. It's been there for a little while now). I believe that the primary cause of my issue was the upgrade from Roots 2 to Roots 3. I didn't notice that it upgraded until things where added/removed from my world when it loaded after the upgrade. I also googled the "roots" thing and basically discounted it as an issue since I was in a sky block world with a very small mob farm (7-10 mobs max at any one time). I'm used to the pausing type lag spikes, but what I was encountering was more like when I hit a mob it was like watching the mob get pushed back in slow motion or clicking on a chest to open it and waiting multiple seconds for it to open.

Thank-you for your help.

**Comment by duely** [comment]
I'm not sure of the exact specifics and I need to double-check with some people who know more about the game than me, but I believe that actually "pausing" the game means that when you unpause it, it tries to catch up and go through everything that should've happened while it was paused. At least, this is what I was experiencing in some test single-player worlds -- but never in a dedicated multiplayer world.

I know there's a gamerule to prevent the game from being paused when you alt-tab, so if this is indeed the case for you, perhaps that's something you could consider trying? Of course, that relies on pausing being the initial cause.

Outside of that, profiling with VisualVM to determine to the source of the issue (or with YourKit or any other product) would be one way to narrow it down, but that requires a little more experience. I'd recommend the FTB subreddit, or any of the modded Minecraft discord servers -- the responses can be flakey depending on who responds, but there are a lot of amazing, awesome people in the community who are willing to help -- and probably know more than I do!
