### ISSUE TITLE
[Effortless Building] Infinite moss scrape setup

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#368]
### General Information

**Describe the bug:**
Scraping the moss off stone turns it into stone. But if your Effortless Building selection is on anything but normal... it fails to replace the block.  I haven't tried Runic Shears or anything else that transforms blocks while giving an item back, but I suspect those areas will fail as well.

While Effortless Building needs to fix its interactions such that right click tools work correctly on 1.12, this could be an interesting problem to try and fix on this end.

**To Reproduce:**
1. Set Effortless Building tool to "Floor" or anything that isn't "Normal" behavior, even "Normal+" works
2. Right click moss stone with knife
3. moss scraped, but there's still a moss block in front of the player

**Expected behavior:**
Detecting the block change first, then awarding items when the block state changes might be necessary instead of assuming that the blockstate will simply change.

***

### Environment Versions
Roots 3.0.21
Effortless Building 2.12

**Comment by noobanidus** [comment]
> assuming that the blockstate will simply change

That's what calling `setBlockState` does. It only ever returns false is the block was *already* at that state, or if something happens during the `shouldRefresh` function to result in the state changing in the meantime. 

I have no idea what Effortless Building is doing, there is absolutely nothing I am *willing* to do in order to attempt to detect interference from a single mod.

Sorry, you'll need to take it up with the Effortless Building people. Feel free to bounce it back to me if they have anything further to say on the matter, but it's...

```java
            world.setBlockState(pos, result);
            world.scheduleBlockUpdate(pos, result.getBlock(), 1, result.getBlock().tickRate(world));
```

Code like this should *not* fail unless the blockstate was already thus or a tile entity (not possible for these blocks) interfered. Effortless Building appear to be breaking this contract.

**Comment by DoomRater** [comment]
As much as I suspected this would be the case, I have no idea why it interferes with setBlockState the way it does, even on modes where this makes no sense.  I've raised an issue but I have to follow it manually. Apparently they won't just take a Google account login.
