### ISSUE TITLE
[mod conflict] Terra Soil yields "Unknown Vis Seeds" from Thaumic Additions

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#383]
Using Roots .25 and Thaumic Additions 23r, I can plant Vis seeds on Terra Soil.  But they use NBT data to store what aspect is in them and this isn't being applied somewhere when the Terra Soil harvests them to produce extra seeds and pods.  The result is "unknown" seeds and pods.

I also need to file a report with Zeith as trying to plant unknown seeds crash the client.

**Comment by noobanidus** [comment]
... wow, that is a complex hot mess. I'm going to have to digest this.

**Comment by noobanidus** [comment]
So, from the look of it, the code was trying to duplicate an ItemStack "quickly" by just making a new one with the same *item* and a different quantity, instead of copying it and setting the quantity. I'm pretty sure that doing so (the copying) will fix the issue, I'm going to close this for now, as I'm aiming to get a 3.1 wide test build out this weekend.
