### ISSUE TITLE
Suggestion: ignore offhand item when taking pestle out of mortar

### ISSUE THREAD

**Issue by Not-February** [EpicSquid/Roots#395]
**Describe your suggestion:**
I can't _begin_ to iterate just how many times I've had to forego having anything at all in my offhand when wandering around my base, all because just taking the pestle out of the mortar when I'm about to use it simultaneously puts whatever is in my offhand into the mortar - while this is annoying even just with the context of the vanilla shield being a valid recipe item, items which don't have any recipes _also_ get put into the mortar upon doing this.

**Describe alternatives you've considered:**
Maybe at the very least, don't have any items from your offhand go into the mortar when you're right-clicking it with an empty main hand to take the pestle out of it? I'd say just only accept items that actually are used in a recipe, but that wouldn't solve the issue with carrying around a vanilla shield since it's used in the Petal Shell spell powder recipe.

**Comment by noobanidus** [comment]
Actually, the issue here is more of a bug. Removing the pestle should cancel the right-click event, making removing the pestle one right-click, and then having to right-click again (with your offhand) to place the item into the mortar.

I'll check into the code, something is obviously failing to return.
