### ISSUE TITLE
An Item Input Suggestion

### ISSUE THREAD

**Issue by JellyGoat** [EpicSquid/Roots#493]
### **Describe your suggestion:**  
It'll certainly become very convenient for automatically doing things if could **add Fay Crafter's input items' support**.

### **Describe alternatives you've considered:**    
If the hopper could input items, it'll be enough.    
Of cource we'll appreciate it that if you add some support for mods like EnderIO and Applied Energistics XD.
  
### **Additional context:**    
  
All the measures I could come up with had been tried three days ago.  
Including hopper, Immersive Engineering's Conveyor Belt, EnderIO's conduits, Applied Energistics's ME Interface and Export bus.

**Comment by noobanidus** [comment]
This is something I've been mulling over for a while, actually. The problem is, each slot can take a full stack of items. So how do you handle inputs from a hopper? Accept one item at a time, and distribute them per slot? It would work for the first recipe, but you'd then need something to determine that the hopper is empty and that you can now put another set of items in...

It's complicated, which is why I haven't added "activate fey crafter" feature to dispensers-using-knives.

On the flip side, in the future, with the elemental grove (focused around automation, amongst other things), or even without, I could do some sort of ritual involving 5 separate containers surrounding a fey crafter with the ingredients, and a chest underneath, and it could take 1 of each and try crafting with it...

Now, that is a much more workable idea.

**Comment by JellyGoat** [comment]
Thx for reply my Suggestion!!!    
Emmm..... A crazy idea would be workable if the hopper could be support.    
It's based on EnderIO's impulse hopper, Extra Utilities' user and hopper.  
The EIO's impulse hopper could output a set of things once.
Then I could use the user to automatically right click crafter with the knife.
But what you said is so fascinating XD.  
It seems like thaumcraft's Infusion. That's very splendid, impresive indeed.

**Comment by noobanidus** [comment]
Actually, the concept is very similar to how the alchemy stand used to be automated in 1.7.10 for Blood Magic -- except you had to specify the item that you were trying to construct -- I can also do it that way, because presumably you have 1 of the thing you're trying to automate.

Alternately, I could make a separate fey crafter designed for automation where you can just put in the item that you want to craft and it will try crafting that... options!

**Comment by noobanidus** [comment]
I'll be delaying this until 3.2 unfortunately. At this point, I just want to get 3.1 released.
