### ISSUE TITLE
Book progress reset

### ISSUE THREAD

**Issue by Gav1nL33** [EpicSquid/Roots#603]
### General Information

**Describe the bug:**
After save and quitting my game, I reloaded it about an hour later, opened my druid book and all my unlocked items are now locked again and can't re-unlock them

**To Reproduce:**

1. Quit game
2. Reload game
3. Open book

**Expected behavior:**
To still have all my progress within the druid book

***

### Environment Versions
3.0.26

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.7.0
- Mystical World: 1.12.2-1.8.3

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): MCEternal version 1.3.7.1

***

**Comment by DoomRater** [comment]
What's your Patchouli version?  The issue seems to be related to Patchouli and we've been talking with their maintainers to try and hammer out why this might be happening only occasionally and seemingly not reproducibly.  The debug versions of Patchouli seem to fix it, but let us know what version of Patchouli you have first.

Or give https://cdn.discordapp.com/attachments/571280713601646602/766070163786170428/Patchouli-1.0-21-debug3.jar a shot and see if it ever happens again.

**Comment by Gav1nL33** [comment]
I'm using Patchouli-1.0-20.jar.
It's the version included within MCEternal

**Comment by noobanidus** [comment]
There's actually a release version of Patchouli that fixes it as well, which is 1.0-22 (I believe).

This is an issue with Patchouli however, not with Roots; updating should fix it.

**Comment by Gav1nL33** [comment]
Is there any way to get my progress back in the book aswell? As when trying to get the entries back it won't work. Or will the update fix that?

**Comment by DoomRater** [comment]
It is as simple as updating Patchouli.  The advancements are actually there, it just failed to load them due to how advancements were loaded on the client.

**Comment by Gav1nL33** [comment]
Thank you

**Comment by noobanidus** [comment]
Basically, Patchouli was loading advancements *before* the server sent them to the client, thus thinking you had no advancements unlocked.
