### ISSUE TITLE
Support Forge 14.23.5.2838

### ISSUE THREAD

**Issue by k1r0s** [EpicSquid/Roots#604]
As many people know, in order to play this mod on a server you need to manage and control what players can / can't do. Hence the use of plugins is required and the only platform is providing so is https://spongepowered.org/

However Roots (and its dependencies) dropped support for it. 

My suggestion is to use 14.23.5.2838 build as many other modders do.

At any case I would like to know why do we require latest forge version.

**Comment by k1r0s** [comment]
I've compiled mysticallib, mysticalworld and roots with Forge 14.23.5.2838. But my modpack runs latest forge on the client. I hope it will work as normal

**Comment by noobanidus** [comment]
> However Roots (and its dependencies) dropped support for it.

Sorry, there's a lot of assumptions and implications here that I'd like to clear up.

a) People play this mod on plenty of servers without running plugins of any kind. I personally have done it many times. There is *no* obligation or requirement to use Sponge plugins; it's merely a preference.
b) I "support" Forge 2847 because it's the latest and last stable release of Forge for 1.12.2. [Here's the changelog](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-changelog.txt) for 2847 which shows the changes since 2838. At the very least, the CMEs with ticket holders is a big thing.
c) Roots has been compiled against 2847 for a very long time, and this is the first time anyone has actually had an issue with this.

I'd recommend you start asking through the Sponge support channels as to why *they* dropped support for 2847 and insist on using 2838. They most likely have explanations on what to do.

I know that there are still ways to run 2838 Sponge with 2847; I know it's a question that was regularly asked on the Astral Sorcery discord, but I forget what the exact solution is.

**Comment by k1r0s** [comment]
To me isn't a mere preference. I need server plugins in order to manage a multiplayer PVP server. 

I do it on my own knowing that it can explode at anytime

thanks for the answer

**Comment by dualspiral** [comment]
Hello, I figured I'd just come in a clear up any confusion so you know where we stand!

> I'd recommend you start asking through the Sponge support channels as to why they dropped support for 2847 and insist on using 2838. They most likely have explanations on what to do.

As Sponge, we just build against 2838, we don't require it. Indeed, we don't insist you use it, we know it works fine with 2847 and we tell people that when they ask. If it bombs out, it's usually due to a misconfiguration, core mod conflict or a problem with multiple mixin versions being shaded, nothing to do with the Forge version.

> I know that there are still ways to run 2838 Sponge with 2847

Just for completeness - you need do nothing but drop the mod in the mods directory - if it fails to launch try prefixing the Sponge jar with `a` as the most likely error is a classloading one where we need a newer version of Mixin which we shade.

Thanks!

**Comment by k1r0s** [comment]
thanks for the answer

**Comment by noobanidus** [comment]
@dualspiral Thanks for the clarification on this matter. I thought that was the case but I wasn't 100% sure and didn't want to promote it as the answer in case I was wrong.
