### ISSUE TITLE
Waxy's Issues with Roots

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#74]
I'v efiltered these issues down to the following:

~~When growing large Baffle Cap it deletes blocks, including bedrock. ~~
~~-Baffle Cap stem drop as item when broken with fist in survival~~
~~-Baffle Cap drop rate from blocks is inconsistent with vanilla large mushroom drop rates (might be intentional)~~
~~-Sky Soarer spell description states floating back to the surface. It's a bit of an unceremonious drop to broken legs.~~
-Growth Infusion spell particle effects are a bit too fastflickery
-Petal Shell has no visual indicator that it is in effect nor it's level. Particles on cast work fine
~~-Wildwood logs drops oak bark when broken with knives~~ Fixed at some point

**Comment by tyler489** [comment]
in order
#63 
#51 
#66
#22 ?
#75 
#67 
#65 
#68 
#69 
Not yet reported
-Thatch is missing recipe
-Baffle Cap entry says use runic shears, can't seem to get working. But not an issue with the crafting method
-When growing large Baffle Cap it deletes blocks, including bedrock.
-Baffle Cap stem drop as item when broken with fist in survival
-Baffle Cap drop rate from blocks is inconsistent with vanilla large mushroom drop rates (might be intentional)
-Sky Soarer spell description states floating back to the surface. It's a bit of an unceremonious drop to broken legs.
-Growth Infusion spell particle effects are a bit too fastflickery
-Petal Shell has no visual indicator that it is in effect nor it's level. Particles on cast work fine
-Are only bark items supposed to drop when breaking logs with a knife
-Wildwood logs drops oak bark when broken with knives

**Comment by duely** [comment]
Okay, I've done what I can with this. One of you get to deal with the remaining particle/graphic ones.
