### ISSUE TITLE
Minecraft crashing on startup

### ISSUE THREAD

**Issue by Juff-Ma** [EpicSquid/Roots#784]
### General Information

**Describe the bug:**

Minecraft is crashing on startup

**To Reproduce:**

1. load theese mods
2. startup

**Expected behavior:**

Minecraft starts
***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.13.0
- Roots: 1.12.2-3.1.4

**Other Versions:**
- Other mods you think could cause issues: requiem/dissolution
- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack (if available): (modpack in testing (want to release))

***

### Logging Information

**Crash Report:** https://pastebin.com/NKaRzqZj

**Comment by Juff-Ma** [comment]
seems to be dublicate of #769

**Comment by DoomRater** [comment]
I was about to say Dissolution shouldn't be the cause, but then I realized I haven't tried them together before- I've used both mods before but in separate packs.

**Comment by noobanidus** [comment]
So it looks like something in the default Summon Creatures recipe for `husk` is being replaced/registry-replaced in such a way that's causing this crash.

The default recipe is: `addSummonCreatureEntry("husk", EntityHusk.class, Ingredient.fromItem(Item.getItemFromBlock(Blocks.CACTUS)), Ingredient.fromItem(Item.getItemFromBlock(Blocks.DEADBUSH)), Ingredient.fromStacks(new ItemStack(Item.getItemFromBlock(Blocks.SANDSTONE), 1, BlockSandStone.EnumType.CHISELED.getMetadata())));`

My recommendation would be to use CraftTweaker to change the recipe for the husk to something different. Unfortunately, the CraftTweaker docs website is down due to Jared's maven having issues.

In the meantime, you can see the current docs on GitHub (without formatting), which has examples for the Summon Creatures recipes: https://github.com/MysticMods/Roots/blob/release/3.1.5/docs/zs/summoncreatures.md

**Comment by Juff-Ma** [comment]
What I wanted to do was change the code I then would have recompile it (I have some modding experience)

**Comment by Juff-Ma** [comment]
But thank you.

**Comment by Juff-Ma** [comment]
fixed it by changing the chiseled sandstone to a normal one.
next problem:
crash report: [https://pastebin.com/ypcqRmG1](https://pastebin.com/ypcqRmG1)

**Comment by Juff-Ma** [comment]
addition: here i really don't see anything but that the field "speed" is private so in first place i don't understand why you can set it (because without extra mods it's running)

**Comment by Juff-Ma** [comment]
the new crash was my fault (not shure why) trying it with crafttweaker

**Comment by mcadventurecity** [comment]
Hello, I am having a similar issue, however using CraftTweaker to remove the recipe doesn't work, as the phase in which the crash occurs is before CraftTweaker scripts run. Below is the link to my crash report.

https://mclo.gs/W0r2aTU
